#!/bin/bash

bluetooth_print() {
    if bluetoothctl show | grep -q "Powered: yes"; then
    
        devices_paired=$(bluetoothctl paired-devices | grep Device | cut -d ' ' -f 2)
        counter=0
    
        device_add=$(echo "$devices_paired" | head -n 1)
        device_info=$(bluetoothctl info "$line")
    
        if echo "$device_info" | grep -q "Connected: yes"; then
    	    device_alias=$(echo "$device_info" | grep "Alias" | cut -d ' ' -f 2-)
    
    	    if [ $counter -gt 0 ]; then
    	        echo "$device_alias"
    	    else
    	        echo "$device_alias"
    	    fi
    
    	    counter=$((counter + 1))
	else
	    echo "On"
        fi
    
    else
        echo "Off"
    fi
}

bluetooth_toggle() {
    if bluetoothctl show | grep -q "Powered: no"; then
        bluetoothctl power on >> /dev/null
        sleep 1

        devices_paired=$(bluetoothctl paired-devices | grep Device | cut -d ' ' -f 2)
        echo "$devices_paired" | while read -r line; do
            bluetoothctl connect "$line" >> /dev/null
        done
    else
        devices_paired=$(bluetoothctl paired-devices | grep Device | cut -d ' ' -f 2)
        echo "$devices_paired" | while read -r line; do
            bluetoothctl disconnect "$line" >> /dev/null
        done

        bluetoothctl power off >> /dev/null
    fi
}

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    bluetooth_toggle
fi

bluetooth_print
