#!/bin/bash

redshift_print() {
    if [ "$(systemctl --user is-active redshift)" == "active" ]; then
        # I use only one color all time, so use temp-day
        if [ -f ~/.config/redshift/redshift.conf ]; then
            echo "$(grep temp-day ~/.config/redshift/redshift.conf | cut -d = -f 2)K"
        # Default is 4500
        else
            # default
            echo "4500K"
        fi
    else
        echo "6500K"
    fi
}

redshift_toggle() {
    if [ "$(systemctl --user is-active redshift)" == "active" ]; then
        systemctl --user stop redshift
    else
        systemctl --user start redshift
    fi
}

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    redshift_toggle
fi

redshift_print
